import { Flex } from '@chakra-ui/react'
import { NextPage } from 'next'
import Head from 'next/head'
import Link from 'next/link'
import { Web3Button } from '../components/Web3Button'
import styles from '../styles/Home.module.css'
import { NftView } from '../components/NftView'
import { ForgeView } from '../components/ForgeView'

const Home: NextPage = () => {

  return (
    <div className={styles.container}>
      <Head>
        <title>Gen Bukowski Forge</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <nav className="flex flex-row justify-between p-4">
        <Link href="/">
          <p className="text-lg font-light">Gen Bukowski Forge</p>
        </Link>
        <Web3Button />
      </nav>
      <Flex>
        <NftView tokenId={0} mintable/>
        <NftView tokenId={1} mintable/>
        <NftView tokenId={2} mintable/>
      </Flex>
      <Flex>
        <NftView tokenId={3} mintable={false}/>
        <NftView tokenId={4} mintable={false}/>
        <NftView tokenId={5} mintable={false}/>
        <NftView tokenId={6} mintable={false}/>
      </Flex>
      <ForgeView/>
    </div>
  )
}

export default Home;